#!/bin/sh /etc/rc.common
# Copyright (c) 2024 OpenWrt.org

START=80

USE_PROCD=1
PROG=/usr/sbin/unetacld

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
